"""Telegram ingestion sidecar — FastAPI entrypoint.

Phase 1 PR-C completes the contract surface with real Telethon calls:

  - `/auth/start` — sends a Telegram login code to the given phone.
  - `/auth/verify` — completes login with SMS code, optionally with the
     2FA password if the account has one.
  - `/chats` — lists groups / supergroups / channels the logged-in
     account is a member of.
  - `/messages` — pulls messages from a chat, cursor-paginated.
  - `/media/{file_unique_id}` — streams a media file by id. This stub
     stays 501 in PR-C because Phase 2 rules-only pipeline does not
     download media; wiring lands when an operator needs it.

Deployment invariant: the sidecar binds to a private network / loopback
and is only reachable by the worker process. Every protected endpoint
requires the `X-Sidecar-Token` header matching `SIDECAR_SHARED_SECRET`.

Session state: Telethon persists a `.session` file per connection_id
under `SIDECAR_SESSION_DIR`. Restarting the sidecar preserves auth for
every connection that has already completed `/auth/verify`.
"""

from __future__ import annotations

import logging
import os
import time
from pathlib import Path
from typing import Optional

import base64
from datetime import datetime, date

from fastapi import FastAPI, Header, HTTPException, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from telethon import TelegramClient
from telethon.errors import (
    ApiIdInvalidError,
    ChannelPrivateError,
    ChatAdminRequiredError,
    FloodWaitError,
    PasswordHashInvalidError,
    PhoneCodeExpiredError,
    PhoneCodeInvalidError,
    PhoneNumberInvalidError,
    SessionPasswordNeededError,
)
from telethon.tl.types import Channel, Chat, Message


SHARED_SECRET_ENV = "SIDECAR_SHARED_SECRET"
API_ID_ENV = "TELEGRAM_API_ID"
API_HASH_ENV = "TELEGRAM_API_HASH"
SESSION_DIR_ENV = "SIDECAR_SESSION_DIR"
DEFAULT_SESSION_DIR = "/var/lib/telegram-sidecar/sessions"
DEFAULT_MESSAGES_LIMIT = 100
MAX_MESSAGES_LIMIT = 500


logger = logging.getLogger("telegram-sidecar")
logging.basicConfig(level=os.environ.get("SIDECAR_LOG_LEVEL", "INFO"))


# ─── In-process state ────────────────────────────────────────────────────────
#
# One `TelegramClient` per `connection_id`. Clients are created lazily,
# connect on first use, and stay open for the lifetime of the process.
# Pending-auth state (phone + phone_code_hash between /auth/start and
# /auth/verify) is kept in a dict here too; operators restarting the
# sidecar mid-login lose the pending state and must start again, which
# is safer than persisting a half-auth to disk.

_clients: dict[str, TelegramClient] = {}
_pending_auth: dict[str, dict] = {}


# ─── Helpers ─────────────────────────────────────────────────────────────────


def _require_token(x_sidecar_token: Optional[str]) -> None:
    expected = os.environ.get(SHARED_SECRET_ENV, "").strip()
    if not expected:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="sidecar misconfigured: SIDECAR_SHARED_SECRET not set",
        )
    if not x_sidecar_token or x_sidecar_token != expected:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid or missing X-Sidecar-Token",
        )


def _api_credentials() -> tuple[int, str]:
    api_id_raw = os.environ.get(API_ID_ENV, "").strip()
    api_hash = os.environ.get(API_HASH_ENV, "").strip()
    if not api_id_raw or not api_hash:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "sidecar misconfigured: TELEGRAM_API_ID and TELEGRAM_API_HASH "
                "must be set (register at https://my.telegram.org/apps)"
            ),
        )
    try:
        return int(api_id_raw), api_hash
    except ValueError as err:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="TELEGRAM_API_ID must be numeric",
        ) from err


def _session_dir() -> Path:
    path = Path(os.environ.get(SESSION_DIR_ENV, DEFAULT_SESSION_DIR))
    path.mkdir(parents=True, exist_ok=True)
    return path


def _session_path(connection_id: str) -> Path:
    # Guard against path traversal: reject anything that would escape
    # the session dir. `connection_id` is a cuid generated by the
    # worker, so in practice it's always safe, but the admin surface
    # is too sensitive for an implicit trust.
    if not connection_id or "/" in connection_id or ".." in connection_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="invalid connection_id",
        )
    return _session_dir() / f"{connection_id}.session"


async def _get_client(connection_id: str) -> TelegramClient:
    client = _clients.get(connection_id)
    if client is not None:
        if not client.is_connected():
            await client.connect()
        return client
    api_id, api_hash = _api_credentials()
    session_file = _session_path(connection_id)
    client = TelegramClient(str(session_file.with_suffix("")), api_id, api_hash)
    await client.connect()
    _clients[connection_id] = client
    return client


async def _require_authorized(client: TelegramClient) -> None:
    if not await client.is_user_authorized():
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="connection not authorized — call /auth/start + /auth/verify first",
        )


def _chat_kind(entity) -> Optional[str]:
    """Map a Telethon entity to the contract's chat kind.

    Returns `None` for chat types the ingestion contract does not
    handle (private DMs, bot chats, etc.) so the caller can filter
    them out.
    """
    if isinstance(entity, Channel):
        return "CHANNEL" if entity.broadcast else "SUPERGROUP"
    if isinstance(entity, Chat):
        return "GROUP"
    return None


def _format_message(message: Message) -> dict:
    """Serialize a Telethon `Message` into the worker's RawTelegramMessage.

    We preserve the original dict under `raw` so the extractor can
    reach into provider-specific fields later if it ever needs to.
    """
    media_entries: list[dict] = []
    media = message.media
    if media is not None:
        kind = "OTHER"
        mime = None
        size = None
        # Minimal mapping — the pipeline doesn't download media yet so
        # we only need enough for the worker to decide whether to
        # enqueue a media-download job. When that lands, extend the
        # mapping to include file_reference.
        if hasattr(media, "photo") and media.photo is not None:
            kind = "PHOTO"
            # Photos: `sizes[-1].size` is the largest variant when present.
            try:
                largest = media.photo.sizes[-1]
                size = getattr(largest, "size", None)
            except (AttributeError, IndexError):
                size = None
        elif hasattr(media, "document") and media.document is not None:
            doc = media.document
            mime = getattr(doc, "mime_type", None)
            size = getattr(doc, "size", None)
            if mime and mime.startswith("video/"):
                kind = "VIDEO"
            else:
                kind = "DOCUMENT"

        # Telethon exposes `file.unique_id` when available; fall back
        # to an id derived from the photo/doc id so the contract's
        # stable identifier is always populated.
        file_unique_id = None
        try:
            file_unique_id = message.file.unique_id if message.file else None
        except AttributeError:
            file_unique_id = None
        if file_unique_id is None:
            base_id = (
                getattr(getattr(media, "photo", None), "id", None)
                or getattr(getattr(media, "document", None), "id", None)
            )
            if base_id is not None:
                file_unique_id = f"tg-{base_id}"
        if file_unique_id:
            media_entries.append(
                {
                    "fileUniqueId": str(file_unique_id),
                    "kind": kind,
                    "mimeType": mime,
                    "sizeBytes": size,
                }
            )

    tg_author_id = message.sender_id
    return {
        "tgMessageId": str(message.id),
        "tgAuthorId": None if tg_author_id is None else str(tg_author_id),
        "text": message.message or None,
        "postedAt": message.date.isoformat() if message.date else None,
        "media": media_entries,
        # Telethon's to_dict() embeds datetime + raw bytes (file
        # references, photo blobs) that the default json encoder
        # cannot serialize. _json_safe normalizes recursively so the
        # extractor still has the full provider payload available.
        "raw": _json_safe(message.to_dict()),
    }


def _json_safe(value):
    """Recursively coerce Telethon payloads into JSON-safe primitives.

    - datetime / date → ISO 8601 string
    - bytes → base64 string (binary file references stay losslessly recoverable)
    - dict / list / tuple → recurse
    Anything else passes through; json.dumps will surface unknown types.
    """
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, (bytes, bytearray)):
        return base64.b64encode(bytes(value)).decode("ascii")
    if isinstance(value, dict):
        return {k: _json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(v) for v in value]
    return value


# ─── App ─────────────────────────────────────────────────────────────────────


app = FastAPI(
    title="Telegram ingestion sidecar",
    version="1.0.0-phase1-prc",
    docs_url=None,
    redoc_url=None,
    openapi_url=None,
)


@app.get("/health")
def health() -> dict[str, bool]:
    """Unauthenticated liveness probe."""
    return {"ok": True}


# ─── Auth flow ───────────────────────────────────────────────────────────────


class AuthStartRequest(BaseModel):
    connection_id: str
    phone_number: str


class AuthVerifyRequest(BaseModel):
    connection_id: str
    code: str
    # Optional 2FA password. Only required if `/auth/verify` returns
    # 409 with `password_required=true`. Operators retry the same
    # request with this field populated.
    password: Optional[str] = None


@app.post("/auth/start")
async def auth_start(
    body: AuthStartRequest,
    x_sidecar_token: Optional[str] = Header(default=None),
) -> JSONResponse:
    _require_token(x_sidecar_token)
    client = await _get_client(body.connection_id)
    try:
        sent = await client.send_code_request(body.phone_number)
    except PhoneNumberInvalidError:
        raise HTTPException(status_code=400, detail="phone number invalid")
    except ApiIdInvalidError:
        raise HTTPException(
            status_code=503,
            detail="TELEGRAM_API_ID / TELEGRAM_API_HASH rejected by Telegram",
        )
    except FloodWaitError as err:
        # Telethon's FloodWaitError always carries `.seconds`.
        return JSONResponse(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            headers={"Retry-After": str(err.seconds)},
            content={
                "error": "telegram flood wait",
                "retry_after_seconds": err.seconds,
            },
        )

    _pending_auth[body.connection_id] = {
        "phone": body.phone_number,
        "phone_code_hash": sent.phone_code_hash,
        "started_at": time.time(),
    }
    return JSONResponse(
        status_code=200,
        content={
            "ok": True,
            "message": "code sent; POST /auth/verify with the code",
        },
    )


@app.post("/auth/verify")
async def auth_verify(
    body: AuthVerifyRequest,
    x_sidecar_token: Optional[str] = Header(default=None),
) -> JSONResponse:
    _require_token(x_sidecar_token)
    pending = _pending_auth.get(body.connection_id)
    if pending is None:
        raise HTTPException(
            status_code=400,
            detail="no pending auth for this connection_id — call /auth/start first",
        )

    client = await _get_client(body.connection_id)
    try:
        await client.sign_in(
            phone=pending["phone"],
            code=body.code,
            phone_code_hash=pending["phone_code_hash"],
        )
    except PhoneCodeInvalidError:
        raise HTTPException(status_code=400, detail="code invalid")
    except PhoneCodeExpiredError:
        raise HTTPException(status_code=400, detail="code expired — call /auth/start again")
    except SessionPasswordNeededError:
        # Account has 2FA (Telegram's "Two-Step Verification"). The
        # operator retries with `password` populated.
        if not body.password:
            return JSONResponse(
                status_code=status.HTTP_409_CONFLICT,
                content={
                    "error": "password required",
                    "password_required": True,
                },
            )
        try:
            await client.sign_in(password=body.password)
        except PasswordHashInvalidError:
            raise HTTPException(status_code=400, detail="2FA password invalid")
    except FloodWaitError as err:
        return JSONResponse(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            headers={"Retry-After": str(err.seconds)},
            content={
                "error": "telegram flood wait",
                "retry_after_seconds": err.seconds,
            },
        )

    _pending_auth.pop(body.connection_id, None)
    return JSONResponse(
        status_code=200,
        content={"ok": True, "authorized": True},
    )


# ─── Read endpoints ──────────────────────────────────────────────────────────


class ChatsRequest(BaseModel):
    connection_id: str
    limit: Optional[int] = None


class MessagesRequest(BaseModel):
    connection_id: str
    tg_chat_id: str
    from_message_id: Optional[str] = None
    limit: int = DEFAULT_MESSAGES_LIMIT


@app.post("/chats")
async def chats(
    body: ChatsRequest,
    x_sidecar_token: Optional[str] = Header(default=None),
) -> JSONResponse:
    _require_token(x_sidecar_token)
    client = await _get_client(body.connection_id)
    await _require_authorized(client)

    try:
        dialogs = await client.get_dialogs(limit=body.limit)
    except FloodWaitError as err:
        return JSONResponse(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            headers={"Retry-After": str(err.seconds)},
            content={"error": "telegram flood wait", "retry_after_seconds": err.seconds},
        )

    out: list[dict] = []
    for dlg in dialogs:
        entity = dlg.entity
        kind = _chat_kind(entity)
        if kind is None:
            continue  # private DM, bot, etc — not in ingestion scope
        # Telethon exposes `dlg.id` as a signed Python int for supergroups
        # / channels (prefixed with -100... for those). Preserve that
        # exactly; the worker stores it as BigInt.
        out.append(
            {
                "tgChatId": str(dlg.id),
                "title": dlg.name or getattr(entity, "title", "") or "",
                "kind": kind,
            }
        )
    return JSONResponse(status_code=200, content={"chats": out})


@app.post("/messages")
async def messages(
    body: MessagesRequest,
    x_sidecar_token: Optional[str] = Header(default=None),
) -> JSONResponse:
    _require_token(x_sidecar_token)
    limit = max(1, min(body.limit, MAX_MESSAGES_LIMIT))
    client = await _get_client(body.connection_id)
    await _require_authorized(client)

    try:
        chat_id = int(body.tg_chat_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="tg_chat_id must be numeric")

    # Cursor semantics match the contract: `from_message_id` is the
    # last seen message id; the worker wants the NEXT batch in
    # ascending order. Telethon's `min_id` delivers exactly that.
    min_id = 0
    if body.from_message_id:
        try:
            min_id = int(body.from_message_id)
        except ValueError:
            raise HTTPException(status_code=400, detail="from_message_id must be numeric")

    try:
        entity = await client.get_entity(chat_id)
    except (ChannelPrivateError, ChatAdminRequiredError):
        raise HTTPException(status_code=404, detail="chat gone or access revoked")
    except ValueError:
        # Telethon raises ValueError("Could not find the input entity")
        # when the client doesn't see the chat in its dialogs.
        raise HTTPException(status_code=404, detail="chat gone")
    except FloodWaitError as err:
        return JSONResponse(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            headers={"Retry-After": str(err.seconds)},
            content={"error": "telegram flood wait", "retry_after_seconds": err.seconds},
        )

    try:
        collected: list[dict] = []
        async for tg_msg in client.iter_messages(
            entity=entity,
            min_id=min_id,
            limit=limit,
            reverse=True,  # ascending by id, so the cursor advances forward
        ):
            collected.append(_format_message(tg_msg))
    except FloodWaitError as err:
        return JSONResponse(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            headers={"Retry-After": str(err.seconds)},
            content={"error": "telegram flood wait", "retry_after_seconds": err.seconds},
        )
    except (ChannelPrivateError, ChatAdminRequiredError):
        raise HTTPException(status_code=404, detail="chat gone or access revoked")

    next_from = collected[-1]["tgMessageId"] if collected else None
    return JSONResponse(
        status_code=200,
        content={
            "messages": collected,
            "nextFromMessageId": next_from,
        },
    )


@app.get("/media/{file_unique_id}")
def media(
    file_unique_id: str,
    x_sidecar_token: Optional[str] = Header(default=None),
) -> JSONResponse:
    """Media download is deliberately deferred.

    Phase 2 rules-only pipeline does not consume media, so wiring
    Telethon's download_media here without an active consumer would
    just add surface area. When an operator needs it we'll cache
    (file_unique_id → file_reference) from /messages and resolve
    downloads against that cache.
    """
    _require_token(x_sidecar_token)
    _ = file_unique_id
    return JSONResponse(
        status_code=status.HTTP_501_NOT_IMPLEMENTED,
        content={
            "error": "media download not implemented — pipeline does not consume media yet",
        },
    )


# ─── Shutdown ────────────────────────────────────────────────────────────────


@app.on_event("shutdown")
async def on_shutdown() -> None:
    """Release Telethon connections cleanly so sessions flush to disk."""
    for client in _clients.values():
        try:
            await client.disconnect()
        except Exception as err:  # noqa: BLE001 - best-effort shutdown
            logger.warning("telethon disconnect failed: %s", err)
